name: Synchronize Action Items
on:
  issues:
    types: [labeled]


jobs:
  Sync-Action-Items:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync Ation Items"
        id: sync_action_items
        uses: link-/gh-issues-ltt@v0.1.4-beta
        if: ${{ contains(github.event.issue.labels.*.name, 'sync_issue') }}
        with:
          owner: "${{ github.actor }}"
          repo: "${{ github.event.repository.name }}"
          issueNumber: "${{ github.event.issue.number }}"
          aggregateIssueLabel: "gh-issues-ltt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}